# DATA601 Homework Assignment 6
Due Date: Sunday, December 5, 23:50 PM

In [1]:
import re

#### Q1
Write a regexp that will find all the Data Science courses mentioned in the following sentence. <br>
<code> sentence1 = 'So far, I took DATA 601, DATA 604, and DATA 605. Next semester I will take DATA 602.'</code> <br>
such that the output will look like <br>
<code> ['DATA 601', 'DATA 604', 'DATA 605', 'DATA 602'] </code>

In [2]:
sentence1 = 'So far, I took DATA 601, DATA 604, and DATA 605. Next semester I will take DATA 602.'
# Answer

r = re.compile(r"DATA 60[0-9]")
newlist = r.findall(sentence1)
print(newlist)

['DATA 601', 'DATA 604', 'DATA 605', 'DATA 602']


### Q2
Write a regexp that will find all the Data Science courses mentioned in the following sentence. <br>
<code> sentence2 = 'So far, I took DATA601, DATA-604, and DATA 605. Next semester I will take DATA602.'</code><br>
such that the output will look like <br>
<code> ['DATA601', 'DATA-604', 'DATA 605', 'DATA602'] </code>

In [3]:
sentence2 = 'So far, I took DATA601, DATA-604, and DATA 605. Next semester I will take DATA602.'
# Answer
r = re.compile(r"DATA.?60[0-9]")
newlist = r.findall(sentence2)
print(newlist)

['DATA601', 'DATA-604', 'DATA 605', 'DATA602']


### Q3
Write a regexp that will find all the graduate courses mentioned in the following sentence. <br>
<code> sentence3 = 'So far, I took DATA 601, ENMG 652, and DATA 605. Next semester I will take DATA 602.'</code><br>
such that the output will look like <br>
<code> ['DATA 601', 'ENMG 652', 'DATA 605', 'DATA 602'] </code>

In [4]:
sentence3 = 'So far, I took DATA 601, ENMG 652, and DATA 605. Next semester I will take DATA 602.'
# Answer


r = re.compile(r"[a-zA-Z]{4}.?6[0-9][0-9]")
newlist = r.findall(sentence3)
print(newlist)

['DATA 601', 'ENMG 652', 'DATA 605', 'DATA 602']


#### Q4
Write a regexp that will match any Python Notebook (.ipynb) file in the following list. <br>
<code> Files = ['lecture1.ipynb','lecture2.ipynb','lecture3.doc','lecture4.py','solutions.ipynb'] </code> <br>
and print the list, e.g. your output will look like <br>
<code>['lecture1.ipynb', 'lecture2.ipynb', 'solutions.ipynb']</code>

In [5]:
Files = ['lecture1.ipynb','lecture2.ipynb','lecture3.doc','lecture4.py','solutions.ipynb']
# Answer
r = re.compile(r"[^ ]+\.ipynb")
newlist = list(filter(r.match, Files)) 
print(newlist)

['lecture1.ipynb', 'lecture2.ipynb', 'solutions.ipynb']


#### Q5
Create a regexp which detects Microsoft Word file names (either *.doc or *.docx) which contain at a numeral, and print their names for the following list <br>
<code>Files2 = ['hw1.docx','hw2.docx','hw3.py','hw_last.docx','hw5.doc'] </code>

In [6]:
Files2 = ['hw1.docx','hw2.docx','hw3.py','hw_last.docx','hw5.doc']
# Answer
r = re.compile(r"[^ ]+\d.doc")
newlist = list(filter(r.match, Files2)) 
print(newlist)

['hw1.docx', 'hw2.docx', 'hw5.doc']


### Q6. 
Compile a pattern that matches with web-addresses in the following sentence. <br> 
<code> sentence = 'Google\'s address is www.google.com.' </code>

In [14]:
sentence = 'Google\'s address is www.google.com.'
pattern = r'[(http://)|\w]*?[\w]*\.[-/\w]*\.\w*[(/{1})]?[#-\./\w]*[(/{1,})]?'
re.findall(pattern, sentence)

#re.findall("", sentence, flags=re.IGNORECASE)

['www.google.com.']

### Q7
Extract all the words in the following sentence <br>
<code>sentence = 'OMG! There is a punctuation. I want to remove it?'</code> <br>
The output should look like this <br>
<code> ['OMG', 'There', 'is', 'a', 'punctuation', 'I', 'want', 'to', 'remove', 'it'] </code>

In [8]:
sentence = 'OMG! There is a punctuation. I want to remove it?'
# Answer

re.findall('[a-z]+', sentence, flags=re.IGNORECASE)

['OMG', 'There', 'is', 'a', 'punctuation', 'I', 'want', 'to', 'remove', 'it']